### ISSUE TITLE
Creating large mrcfile with memmap

### ISSUE THREAD

**Issue by imaluengo** [ccpem/mrcfile#1]
I was trying to copy an existing HDF5 file to MRC format. The HDF5 file is too big. I could use the existing mechanism to dump the whole HDF5 dataset to an MRC file as:

    with mrcfile.new('tmp.mrc') as mrc:
        mrc.set_data(large_hdf5[...], dtype=np.float32))

However, that requires me to load the whole HDF5 file into memory. A similar problem arises if I want to initialize an empty MRC file (similar to `np.zeros`) of size larger than RAM (e.g. 4000x4000x4000), it would require me to create `np.zeros((4000,4000,4000))` beforehand, which is a bit redundant.

This can be solved using memmaps, which is what I tend to use when h5py is not available/needed.

By inspection/reverse engineering I managed to come up with the following code which will initialize an empty dataset without requiring to create it with numpy beforehand:

    import mrcfile as mrc
    import numpy as np

    def newmrc(fpath, shape, dtype, fill=None):
        f = mrc.MrcMemmap(fpath, mode='w+', overwrite=True)
        dsize = np.prod(shape) * np.dtype(dtype).itemsize   # data size
        hsize = f.header.nbytes + f.header.nsymbt           # header size
        f._iostream.truncate(hsize + dsize)
        f._open_memmap(dtype, shape)
        f.update_header_from_data()
        f.update_header_stats()
        if fill is not None:
            f.data[...] = fill
        return f

That would allow you to create a memmaped MRC without having to hold a very large array in memory beforehand. You could then apply any chunking mechanism to write the full file, e.g.:

    # array on disk full of zeros
    f = newmrc('/tmp/test.mrc', (2000, 2000, 2000), np.float32, fill=0)

It will take time (a lot) to write a 30GB file, but it will do it without memory problems.

I thought it was useful to share the script, because 1) maybe I'm missing something important or 2) it might be useful to add to the library itself or 3) there might be a better alternative to what I want to achieve but I failed to find it.

**Comment by colinpalmer** [comment]
Thanks Imanol. It's definitely a good idea to have this ability in the library, either as a function or a code example in the documentation. Your code looks like a good starting point, but I think I've done something similar for my own use in the past, too - I'll see if I can find that and compare them, then make a good, general-purpose version for public use.

**Comment by imaluengo** [comment]
I was just testing the script, and it does indeed still use too much RAM to store zeroes:

    f = newmrc('/tmp/test.mrc', (2000, 2000, 2000), np.float32, fill=0)

So there has to be a better way of writing big chunks of data :) Let me know if you find something better!

**Comment by colinpalmer** [comment]
Your code works if you remove the `f.update_header_stats()` line. (That reads the entire data block to generate summary statistics, but it causes problems with big data arrays and isn't required.)

Did you test it without the file truncation, too? I'm not sure if that's required or not when you're just creating a new file, I think the main reason it's done in the library code is to cover the case of making an existing file smaller.

I expect the following should work nicely (and if it doesn't, I'd like to know!): 

```
def newmrc(fpath, shape, dtype, fill=None):
    f = mrc.MrcMemmap(fpath, mode='w+', overwrite=True)
    f._open_memmap(dtype, shape)
    f.update_header_from_data()
    if fill is not None:
        f.data[...] = fill
    return f
```

**Comment by imaluengo** [comment]
Just a minor problem with your code: with `fill=None` it does create a 8KB file with no content at all.

Other than that it works fine, as expected!

**Comment by colinpalmer** [comment]
OK, useful to know, thanks!

**Comment by colinpalmer** [comment]
This has (finally!) been done. The code is now in GitHub and will be in the next mrcfile release.
