### ISSUE TITLE
Any reason for a flip in y

### ISSUE THREAD

**Issue by pconesa** [ccpem/mrcfile#10]
We are seeing a weird behaviour, or maybe not, when Cryolo, that uses this module, reads a MRC file that , wronlgy has 1 in the ispg word being a 2d image not a volume: image is visualize flipped in y. Any reason?

**Comment by colinpalmer** [comment]
I would guess the ispg value and the handedness of the data block are independent.

The handedness itself is a bit of a problem (see the "Handedness" section on the [format description page](http://www.ccpem.ac.uk/mrc_format/mrc2014.php)). "Officially" the data array is supposed to be right handed (origin at bottom left, Z axis towards the viewer) but quite a few software packages use the opposite convention. The only real solution is to check the behaviour of each package you need to work with!

**Comment by pconesa** [comment]
Thanks, @colinpalmer . I don't think is a convention issue, since the same software, in this case cryolo, behaves differently base on the value of ispg. In any case, this might not be an mrcfile code issue, so I'm closing the issue. Many thanks again!
