### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by wendingp** [ccpem/mrcfile#15]
value error when I use set_data() on a mrc file
```
Traceback (most recent call last):
  File "test_crop_img.py", line 31, in crop_mrc
    mrc_crop.set_data(mrc.data[z:dz, x:dx, y:dy])  
  File "/ldap_shared/home/v_wending_peng/anaconda3/lib/python3.7/site-packages/mrcfile/mrcobject.py", line 226, in set_data
    self.update_header_stats()
  File "/ldap_shared/home/v_wending_peng/anaconda3/lib/python3.7/site-packages/mrcfile/mrcobject.py", line 446, in update_header_stats
    self.header.dmin = self.data.min()
  File "/ldap_shared/home/v_wending_peng/anaconda3/lib/python3.7/site-packages/numpy/core/_methods.py", line 32, in _amin
    return umr_minimum(a, axis, None, out, keepdims, initial)
ValueError: zero-size array to reduction operation minimum which has no identity
```

**Comment by colinpalmer** [comment]
Thanks for raising this. I can reproduce this error myself if I pass an empty array to set_data(). Is that what's happening in your case?

I'll fix the error with an empty array anyway, but if you're seeing this error and the array you're passing is definitely not empty, please do let me know.

**Comment by wendingp** [comment]
Yeah I checked my case, it's empty.

**Comment by wendingp** [comment]
Btw, I have another question: what is the best way to only modify a mrc's data and save it as **another** mrc file instead of **inplace**? (think about cropping a mrc image, for example)

My current workaround is: copy the mrc file, call set_data() on the new mrc and save it. But the defect is that if the original mrc is large, it takes lots of extra disk space and time to copy the file.

**Comment by colinpalmer** [comment]
I'd normally use `mrcfile.new()` to make a new empty `MrcFile` object, then call `set_data()`, then update other header fields as needed. You'd usually want to copy the voxel size (`new_mrc.voxel_size = old_mrc.voxel_size`), and also possibly adjust `origin` or `nxstart`, `nystart` and `nzstart` if you need the cropped map to appear in the correct location in space relative to the original.

**Comment by wendingp** [comment]
Well, because there are many stuff in the mrc header like nx, xlen, and many of them I actually don't know their meaning, so I'd be cautious to copy and change it to make sure I only modify the data and doesn't miss copying others...

**Comment by colinpalmer** [comment]
I'm afraid you do need to understand a bit about the header to get sensible results! In particular, the voxel size is defined indirectly, by dividing the box size (`cella.x`, `cella.y` and `cella.z` in the [official specification](http://www.ccpem.ac.uk/mrc_format/mrc2014.php), or `xlen` etc. as IMOD calls them) by the number of voxels in each dimension. If you copy an existing file and replace the data with a smaller array, the new data will still fill the same volume and the voxel size will be larger than it was.

For most purposes, it should be fine to do as I suggested before - make a new file, put the data in it, and set the voxel size by copying the source file. That'll set most of the header automatically. If you do need to preserve the origin then you'll need to get into the details a bit more. (Or use another tool - for simple cropping, I'd normally use IMOD's `trimvol` or `newstack` commands.)

**Comment by wendingp** [comment]
Oh ok, thanks. I'll look into it.

**Comment by mikechen66** [comment]
Logical problem in the lines of code also incurs the ValueError: zero-size array.... I met this problem this morning. After I adjusted the logical order, I was able to run the AlexNet model with cropped image scenario.

**Comment by colinpalmer** [comment]
I'm not sure I understand this comment. Which lines of code do you mean, and what is the logical problem?

**Comment by omsingh39** [comment]
![Screenshot 2023-03-20 110038](https://user-images.githubusercontent.com/104888913/226265488-98ba30cd-1b5b-4f96-bae3-11d6679e4e4c.png)
How to correct this error?

**Comment by colinpalmer** [comment]
I don't think this is related to mrcfile, is it? In a general sense, this error means that you've ended up passing an empty array to numpy's `fmin` function, but I don't know any more about how that might have happened in your case.

**Comment by Jango96** [comment]
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[69], line 1
----> 1 time_idx, labels, angles, crossfluxes, result_df = findARs(ivt.data, ivtrec.data,ivtano.data, 
      2                                                            qu.data, qv.data, latax, lonax, 
      3                                                            times=timeax, **PARAM_DICT)

File ~\anaconda3\lib\site-packages\ipart\AR_detector.py:1884, in findARs(ivt, ivtrec, ivtano, qu, qv, lats, lons, times, ref_time, thres_low, min_area, max_area, min_LW, min_lat, max_lat, min_length, min_length_hard, rdp_thres, fill_radius, single_dome, max_ph_ratio, edge_eps, zonal_cyclic, verbose)
   1873 finder_gen = findARsGen(ivt, ivtrec, ivtano, qu, qv, lats, lons,
   1874         times=times, ref_time=ref_time, thres_low=thres_low,
   1875     min_area=min_area, max_area=max_area,
   (...)
   1880     edge_eps=edge_eps, zonal_cyclic=zonal_cyclic,
   1881     verbose=verbose)
   1882 next(finder_gen)  # prime the generator to prepare metadata
-> 1884 for (tidx, timett, label, angle, cross, ardf) in finder_gen:
   1886     time_idx.append(tidx)
   1887     labels_all.append(label)

File ~\anaconda3\lib\site-packages\ipart\AR_detector.py:2073, in findARsGen(ivt, ivtrec, ivtano, qu, qv, lats, lons, times, ref_time, thres_low, min_area, max_area, min_LW, min_lat, max_lat, min_length, min_length_hard, rdp_thres, fill_radius, single_dome, max_ph_ratio, edge_eps, zonal_cyclic, verbose)
   2070     continue
   2072 # find AR axis
-> 2073 axis_list, axismask=findARAxis(quslab, qvslab, mask_list, costhetas,
   2074         sinthetas, reso, param_dict)
   2076 # decompose background-transient
   2077 qurec,quano,qvrec,qvano=uvDecomp(quslab,qvslab,slabrec,slabano)

File ~\anaconda3\lib\site-packages\ipart\AR_detector.py:1401, in findARAxis(quslab, qvslab, armask_list, costhetas, sinthetas, reso, param_dict, verbose)
   1399     gii=maskToGraph(maskii,quii,qvii,cosii,sinii,edge_eps)
   1400     #--------------Get AR axis from graph--------------
-> 1401     axisarrii,axismaskii=getARAxis(gii,quii,qvii,maskii,None)
   1403 if rollii:
   1404     # shift back
   1405     #axismaskii=np.roll(axismaskii, -axismaskii.shape[1]//2, axis=1)
   1406     #newx=(axisarrii[:,1] - axismaskii.shape[1]//2)%axismaskii.shape[1]
   1407     axismaskii=np.roll(axismaskii, -shift_lon, axis=1)

File ~\anaconda3\lib\site-packages\ipart\AR_detector.py:455, in getARAxis(g, quslab, qvslab, mask, edge)
    452         distii=distdict[nodeii]
    453         dists[ii,outedgecoor.index(nodeii)]=distii
--> 455 if np.max(dists)==0:
    456     # this may happen when a mask is touching the map edges, and inedgecoor
    457     # outedgecoor can't be linked by a path. Very rarely happen, but damn
    458     # annoying. A fallback solution is to use an undirected graph linking
    459     # the most inward and most outward pixels.
    460     mostin=np.unravel_index(np.argmax(inedge), mask.shape)
    461     mostout=np.unravel_index(np.argmin(inedge), mask.shape)

File <__array_function__ internals>:180, in amax(*args, **kwargs)

File ~\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:2793, in amax(a, axis, out, keepdims, initial, where)
   2677 @array_function_dispatch(_amax_dispatcher)
   2678 def amax(a, axis=None, out=None, keepdims=np._NoValue, initial=np._NoValue,
   2679          where=np._NoValue):
   2680     """
   2681     Return the maximum of an array or maximum along an axis.
   2682 
   (...)
   2791     5
   2792     """
-> 2793     return _wrapreduction(a, np.maximum, 'max', axis, None, out,
   2794                           keepdims=keepdims, initial=initial, where=where)

File ~\anaconda3\lib\site-packages\numpy\core\fromnumeric.py:86, in _wrapreduction(obj, ufunc, method, axis, dtype, out, **kwargs)
     83         else:
     84             return reduction(axis=axis, out=out, **passkwargs)
---> 86 return ufunc.reduce(obj, axis, dtype, out, **passkwargs)

ValueError: zero-size array to reduction operation maximum which has no identity

**Comment by colinpalmer** [comment]
Sorry, I don't see why what you posted is relevant to mrcfile. If you're having problems with numpy, please read the documentation or raise issues over there, but if it's not directly related to mrcfile I can't do much to help.
