### ISSUE TITLE
Is there any way this can be used in a lazy way?

### ISSUE THREAD

**Issue by markbasham** [ccpem/mrcfile#16]
So I may not want to load all the data into ram, maybe just a subset, is there any way this can be accommodated?

**Comment by colinpalmer** [comment]
Yes, using `mrcfile.mmap()` instead of `mrcfile.open()`. See [this section](https://mrcfile.readthedocs.io/en/latest/usage_guide.html#memory-mapped-files) of the usage guide for more details, and do ask if anything's not clear!

**Comment by markbasham** [comment]
Brilliant, thanks @colinpalmer managed to totally miss that bit in the docs :$
