### ISSUE TITLE
Error when opening MotionCor2 output

### ISSUE THREAD

**Issue by ssscj** [ccpem/mrcfile#19]
Hi developers,
Thanks for this useful package. I met a problem when using it to open a single frame data from MotionCor2. Here is the error.
`In [9]: mrcfile.validate('20200713avg.mrc')`
`/software/anaconda/lib/python3.7/site-packages/mrcfile/mrcinterpreter.py:208: RuntimeWarning: Map ID string not found - not an MRC file, or file is corrupt
  warnings.warn(msg, RuntimeWarning)
Map ID string is incorrect: found b'MAP', should be b'MAP '
Error in data statistics: RMS deviation is 31.696720123291016 but the value in the header is 0.0`
`Out[9]: False`
Thanks for your help.

**Comment by colinpalmer** [comment]
Unfortunately this is a known problem with files from MotionCor2. The file ID string is not quite correct. You can open these files with mrcfile by using the `permissive` argument, for example: `mrcfile.open('20200713avg.mrc', permissive=True)`.

**Comment by ssscj** [comment]
It works, thanks for your help!
