### ISSUE TITLE
Modify `n*start`

### ISSUE THREAD

**Issue by paulkorir** [ccpem/mrcfile#21]
Hi,
Thanks for a very useful package. 
I was wondering whether you could add a way to modify `n*start` params (`nxstart`, `nystart`, `nzstart`) in a manner similar to `voxel_size`. 
Thanks.
Paul

**Comment by colinpalmer** [comment]
Thanks for the suggestion, that's a good idea. I'll try and implement that soon and get a new version out.

**Comment by colinpalmer** [comment]
I've added an `nstart` property now, documented [here](https://mrcfile.readthedocs.io/en/latest/source/mrcfile.html#mrcfile.mrcobject.MrcObject.nstart). At the moment it's only available if you get the `mrcfile` code from GitHub but I'll make a new release including this on PyPI soon.

**Comment by colinpalmer** [comment]
I've made a new release (v1.2.0) that includes the new `nstart` property. It's available from PyPI now and hopefully also soon from conda-forge.

**Comment by paulkorir** [comment]
Fantastic!
