### ISSUE TITLE
Having trouble while saving the image into .TIF

### ISSUE THREAD

**Issue by Yuvi-416** [ccpem/mrcfile#25]
Hi there,
First of all, thank you for this wonderful package in the python environment.
I have downloaded the MRC file from here: https://www.ebi.ac.uk/empiar/EMPIAR-10324/ and was trying to save each slice in a .tif format. The code run very well but the saved image is not very good, you can see the generated image below.
https://uapt33090-my.sharepoint.com/:f:/g/personal/ygupta_ua_pt/Eh0yGt6IzTZOh703l3KY0JcB2zAG46W_TaemNLJNWNk2Dw?e=OJTUtQ
code:
```
i = mrcfile.open(input1)
for ii in range(i.data.shape[0]):
    ii = 43
    tifffile.imwrite(str(output) + f'{ii}.tif', i.data[ii])
```
But when I try to save the MRC image into .tif utilizing the IMOD LINUX package it works perfectly.
Can you help me why I am not getting satisfactory images in python?
Thank you!

**Comment by colinpalmer** [comment]
Hi, I can't easily check the details myself right now, but this looks like
a problem of treating signed byte data as unsigned or vice versa. I would
guess that most likely, the file contains unsigned bytes, but stored in MRC
mode 0 which is officially for signed byte data. IMOD is a bit more
intelligent and corrects this by itself. To do the same in Python, you
probably need to do something like `mrc.data.dtype = numpy.uint8` after
opening the file. Or copy the data into an int16 array and then add 128 to
all values.

**Comment by Yuvi-416** [comment]
Hi there,
I follow your advice. The first option didn't work and the second option worked but it squeezes the x-axis. I don't know whether I add 128 correctly or not.
For example: 
`i.shape = (361, 1670, 1562)` but after applying i.data.dype»»»int16, it squeezes the image width as (1670, 781).

Here's the code:
```
i = mrcfile.open(input1)
i.data.dtype = np.int16
np.append(i.data, 128)

for ii in range(i.data.shape[0]):
    tifffile.imwrite(str(output) + f'{ii}.tif', i.data[ii])
```

**Comment by colinpalmer** [comment]
Instead of np.append, try `i.data += 128`

**Comment by Yuvi-416** [comment]
Thank you!
