### ISSUE TITLE
Correction of the usage guidelines

### ISSUE THREAD

**Issue by MohamadHarastani** [ccpem/mrcfile#27]
There is a mistake in the [README.rst](https://github.com/ccpem/mrcfile/blob/master/README.rst)
`mrc.set_data(np.zeros((5, 5), dtype=np.int8))
`
This doesn't work. From one side, the data type is better to be float32 always (you don't want to confuse people right?). From the other side, dtype is not defined at all. I would write that as:
```
# Saving 2D or 3D matrix in mrc format:
I = np.zeros([5,5]) # your 2D or 3D matrix
out = mrcfile.new('FileName.mrc')
out.set_data(np.float32(I))
out.close()
```
Thanks for sharing your library.

Mohamad

**Comment by colinpalmer** [comment]
Hi, thanks for raising this. The examples in README.rst all work for me; if you're getting an error about dtype not being defined, I think it's most likely that you've put a bracket in the wrong place (dtype is an argument for the `numpy.zeros` function in that example, not the `mrc.set_data` method). You're right that the way it's written does risk causing confusion. I've updated the text to separate the array creation from the `mrc.set_data` call so it should be clearer which arguments are relevant to which function.

(I disagree with you that the dtype should be float32 always: `mrcfile` supports the full MRC2014 standard with all its different MRC data modes, so for me it makes sense to use a range of dtypes in the examples.)
