### ISSUE TITLE
it'd be handy to have validator available from the command line

### ISSUE THREAD

**Issue by wojdyr** [ccpem/mrcfile#3]
For example you could throw in `__main__.py` file:
```py
import sys
from .__init__ import validate

sys.exit(0 if all(validate(path) for path in sys.argv[1:]) else 1)
```

and then one could validate a map as:

    $ python -m mrcfile my.map

**Comment by colinpalmer** [comment]
Thanks for the suggestion, Marcin.

I've now added command line functions for validation and printing the file header. Details and examples are in the [usage guide](http://mrcfile.readthedocs.io/en/latest/usage_guide.html#command-line-usage).
