### ISSUE TITLE
module 'mrcfile' has no attribute 'read'

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [ccpem/mrcfile#39]
Dear all,

I tried to use .read() and .write() methods of mrcfile, but both outputs error:

```
AttributeError: module 'mrcfile' has no attribute 'read'
```
What could possibly be wrong?
I am running it with Python 3.9.0 and mrcfile is 1.3.0.

Best regards,
Aliaksei

**Comment by colinpalmer** [comment]
Sorry, the problem here was that the read and write functions were added in the code here on GitHub and the docs on ReadTheDocs, but I hadn't made a new release on PyPI. There is a new release now, so if you install mrcfile 1.4 it should all work nicely.
