### ISSUE TITLE
Does mrcfile read maps using data dtype according to ccp4 mode when memory mapping is used?

### ISSUE THREAD

**Issue by aliaksei-chareshneu** [ccpem/mrcfile#46]
Dear all,

Could you tell me please if mrcfile read map with data dtype according to ccp4 mode, when memory mapping is used?
E.g., if I do:
```
with mrcfile.mmap(map_file) as mrc_original:
        data: np.memmap = mrc_original
```
where `map_file` is map with certain mode, will the `data` have the dtype corresponding to that mode?

**Comment by colinpalmer** [comment]
Yes, the dtype is always set according to the map mode, and there should be no difference between the dtypes when the file is opened normally or with mmap.

**Comment by aliaksei-chareshneu** [comment]
@colinpalmer, thanks a lot.
