### ISSUE TITLE
Mismatch in supported modes between documentation and code

### ISSUE THREAD

**Issue by dtegunov** [ccpem/mrcfile#56]
The [documentation](https://mrcfile.readthedocs.io/en/stable/usage_guide.html) says "Currently accepted modes are 0, 1, 2, 4 and 6", but mode 12 (float16) is supported in the current version of the code.

**Comment by colinpalmer** [comment]
Thanks! Fixed now.

**Comment by colinpalmer** [comment]
And now fixed in the docs build too.
