### ISSUE TITLE
How to use header information

### ISSUE THREAD

**Issue by XiaoChen1992** [ccpem/mrcfile#57]
Hi, 

I used Chimear to superimpose two density maps  (A, B, I fit A to B) and save the superimposed one (B) as a new mrc file (C). But when I use mrcfile package to read it (C), how could I use header information to ensure the mrc.data is superimposed? If I directly load mrc.data as an array, it is the same the mrc.data of the original map (B).

Thank you

**Comment by colinpalmer** [comment]
The MRC header has a couple of ways of defining an offset for a map: `mrc.header.origin` and the `nstart` fields (`mrc.header.nxstart`, `...nystart`, `...nzstart`) so you should check those. After fitting in Chimera I would expect the `nstart` fields would be zero and `origin` might be non-zero, but it's a good idea to check both and make sure.

It's also possible (but unlikely) that one of the maps might have transposed axes, which would make it look like the density is not aligned. That's defined in `mrc.header.mapc`, `mapr` and `maps`, you should check that the maps you're comparing have the same values in those.

But, it could be that it's a different cause in your case. The origin field can only apply translations, so if Chimera made any rotations to fit the maps, it couldn't use the origin to save the result. From what you said, I wonder if you might have saved the wrong map. If you fitted A to B, then saved B, you could have saved an unchanged copy of map B, and so it wouldn't be surprising that it's still the same as the original map B. If you try fitting A to B and then saving map A, is that any better?
