### ISSUE TITLE
What is the license of the official spec?

### ISSUE THREAD

**Issue by KOLANICH** [ccpem/mrcfile#6]
I wonder if you are going to license it under public domain to make copying the parts of [the spec](http://www.ccpem.ac.uk/mrc_format/mrc2014.php) (the docs) into source code legal.

**Comment by colinpalmer** [comment]
Unfortunately the copyright status of the spec is unclear - parts of the text have been written by different people working for various different organisations over many years. It seems no-one was ever particularly worried about its copyright or licencing status. So, I don't think we're able put it into the public domain, but equally I don't think anyone is going to object if you copy parts of it in source code.

**Comment by KOLANICH** [comment]
>Unfortunately the copyright status of the spec is unclear - parts of the text have been written by different people working for various different organisations over many years.

It's very unfortunately: this mean we cannot use the spec parts not covered by limitations to copyright, such as text. We will either have to create the new docs, or just throw them away.

>It seems no-one was ever particularly worried about its copyright or licencing status. 

In an ideal world noone cares about copyright because there is no such a thing (and my personal opinion that copyright, patents and similar things must be abolished). But since we are doing an open-source projects which should be suitable for everyone, and since it is not abolished yet, we have to worry about it.

> So, I don't think we're able put it into the public domain, but equally I don't think anyone is going to object if you copy parts of it in source code.

Could you contact all the copyright holders involved (I don't think it is a big problem since there is email and messengers) and ask them to dedicate their copyrighted share into public domain? I don't want my labour be wasted and I don't want to be prosecuted for sharing my work.

**Comment by colinpalmer** [comment]
The problem is, I don't think we even know ourselves who wrote which parts of the text originally, so it isn't really possible to contact the copyright holders.

I'm not a legal expert, but I would have thought that quoting snippets of the spec in documentation would count as fair use for copyright purposes anyway. And if you're quoting the entirety of the text it might be better to just refer to the URL of the spec online?

**Comment by KOLANICH** [comment]
>I'm not a legal expert, but I would have thought that quoting snippets of the spec in documentation would count as fair use for copyright purposes anyway. And if you're quoting the entirety of the text it might be better to just refer to the URL of the spec online?

In fact I have created an own spec based on the original one. But there is a difference: it is written in a formal language, it contains nearly everything the original spec contains (except the text, and I wanna put there the text too, because without it it won't be a good spec) and ambiguity is resolved - that spec can be compiled into a ready to use parser in c++, java, scala, rust, python (2 differrent runtimes, one of them may allow serializing data back to binary, but I have not tested that, also I have not pluged that into this lib instead of currently used handwritten parser because of lack of time, but it's planned) , javascript, lua. Also it can be compiled into a GraphViz .dot file. I wanna it replace the original spec - it will be better for everyone if you further develop the spec as that file.

**Comment by milliams** [comment]
It looks like the spec at http://www.ccpem.ac.uk/mrc_format/mrc2014.php is based on the [Cheng et al. (2015)](https://doi.org/10.1016/j.jsb.2015.04.002) paper which has a license of [CC-BY 4.0](https://creativecommons.org/licenses/by/4.0/). So while the code in this repo may have a busy history, the spec itself is clearly licensed.

**Comment by colinpalmer** [comment]
Thanks - I hadn't though to check the licence for the paper itself but that clears things up quite a lot. The status of the code in this repo is actually very clear: it's all copyright STFC and BSD-licenced. The remaining area of confusion is the text of the spec on the CCP-EM website, but we can perhaps now deal with that by making sure all of the text was either written originally by us or adjusting it to quote from the paper under the CC-BY licence.

**Comment by KOLANICH** [comment]
Has the license question been resolved? What license should I apply to the Kaitai Struct spec written by me but based on your specs, both from this repo and the website? SFTC, BST, CC-BY-4.0 or what?

**Comment by colinpalmer** [comment]
The licensing situation is the same as it was. The source code in this repository (including comments, docs, docstrings etc) are freely available for redistribution and reuse under the terms of the [BSD licence](https://github.com/ccpem/mrcfile/blob/master/LICENSE.txt). Text and definitions from the [MRC2014 paper](https://doi.org/10.1016/j.jsb.2015.04.002) are available under the [CC-BY-4.0](https://creativecommons.org/licenses/by/4.0/) licence.

The [MRC2014 page](http://www.ccpem.ac.uk/mrc_format/mrc2014.php) on the CCP-EM website does not currently have an open licence, so normal copyright applies. If that text is updated in future we will try to take the opportunity to make it available more openly. But in the meantime, I expect you should be able to find everything you need from the paper and/or this repo.

**Comment by KOLANICH** [comment]
Thanks for the clarification.
